os: linux
language: cpp
notifications:
  email: false

matrix:
  include:

    # Clang 6.0
    - name: "Trusty Clang 6.0"
      env: COMPILER=clang++-6.0
      dist: trusty
      addons: &clang60
        apt:
          packages:
            - clang-6.0
            - g++-7
            - libhwloc-dev
            - libopenmpi-dev
            - libtool
            - openmpi-bin
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    # GCC 7
    - name: "Trusty GCC 7"
      env: COMPILER=g++-7
      dist: trusty
      addons: &gcc7
        apt:
          packages:
            - g++-7
            - libhwloc-dev
            - libopenmpi-dev
            - libtool
            - openmpi-bin
          sources:
            - ubuntu-toolchain-r-test

    # GCC 7
    - name: "Xenial GCC 7"
      env: COMPILER=g++-7
      dist: xenial
      addons: &gcc7
        apt:
          packages:
            - g++-7
            - libopenmpi-dev
            - libtool-bin
          sources:
            - ubuntu-toolchain-r-test

install:
  - export CXX=${COMPILER}
  - ./install-deps.sh
before_script:
  - cd tests
script:
  - make test
