os: linux
dist: xenial

matrix:
  include:
    - language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_script:
        - mkdir -p archives
      script:
        - ./setup.sh

    - language: python
      python: 3.6
      before_script:
        - cd tests
      script:
        - python3 boilerplate/generate_g.py

before_install:
    - eval "${MATRIX_EVAL}"
