os: linux
language: cpp
notifications:
  email: false

matrix:
  include:

    # Clang 6.0
    - name: "Trusty Clang 6.0"
      env: _CXX=clang++-6.0
      dist: trusty
      addons: &clang60
        apt:
          packages:
            - clang-6.0
            - g++-7
            - libhwloc-dev
            - libopenmpi-dev
            - libtool
            - openmpi-bin
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    # GCC 7
    - name: "Trusty GCC 7"
      env: _CXX=g++-7
      dist: trusty
      addons: &gcc7
        apt:
          packages:
            - g++-7
            - libhwloc-dev
            - libopenmpi-dev
            - libtool
            - openmpi-bin
          sources:
            - ubuntu-toolchain-r-test

    # GCC 7
    - name: "Xenial GCC 7"
      env: _CXX=g++-7
      dist: xenial
      addons: &gcc7
        apt:
          packages:
            - g++-7
            - libopenmpi-dev
            - libtool-bin
          sources:
            - ubuntu-toolchain-r-test

    # Python 3
    - name: "Xenial Python 3"
      dist: xenial
      language: python
      python: 3.6

install:
  - |
    if [[ ! -z "${_CXX}" ]]; then
      export CXX=${_CXX}
      curl -L https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0.tar.gz | tar xz
      cd cmake-3.14.0 && cmake . && make -j2 && sudo make install
      cd ${TRAVIS_BUILD_DIR}
      ./install-deps.sh
    fi
before_script:
  - cd tests
script:
  - |
    [[ ! -z "${_CXX}" ]] && make unit-test || make generate-test
