matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - language: python
      python: 3.6
      before_script:
      - cd tests
      script:
      - python3 boilerplate/generate_g.py