dist: xenial
sudo: required

matrix:
  include:
    - language: cpp
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_script:
        - mkdir -p archives && ./setup.sh

    - language: python
      python: 3.6
      before_script:
        - cd tests
      script:
        - python3 boilerplate/generate_g.py
