os: linux
dist: xenial
language: cpp

matrix:
  include:

    # --------------- Clang on Linux --------------- #

    # Clang 6
    - name: "Clang 6"
      env: _CXX=clang++-6.0
      addons:
        apt:
          packages:
            - clang-6.0
            - libhwloc-dev
            - libopenmpi-dev
            - libtool
            - openmpi-bin
          sources:
            - llvm-toolchain-xenial-6.0

    # Clang 7
    - name: "Clang 7"
      env: _CXX=clang++-7
      addons:
        apt:
          packages:
            - clang-7
            - libhwloc-dev
            - libopenmpi-dev
            - libtool
            - openmpi-bin
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7

    # Clang 8
    - name: "Clang 8"
      env: _CXX=clang++-8
      addons:
        apt:
          packages:
            - clang-8
            - libhwloc-dev
            - libopenmpi-dev
            - libtool
            - openmpi-bin
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8

    # --------------- GCC on Linux --------------- #

    # GCC 6
    - name: "GCC 6"
      env: _CXX=g++-6
      addons:
        apt:
          packages:
            - g++-6
            - libhwloc-dev
            - libopenmpi-dev
            - libtool-bin
          sources:
            - ubuntu-toolchain-r-test

    # GCC 7
    - name: "GCC 7"
      env: _CXX=g++-7
      addons:
        apt:
          packages:
            - g++-7
            - libhwloc-dev
            - libopenmpi-dev
            - libtool-bin
          sources:
            - ubuntu-toolchain-r-test

    # GCC 8
    - name: "GCC 8"
      env: _CXX=g++-8
      addons:
        apt:
          packages:
            - g++-8
            - libhwloc-dev
            - libopenmpi-dev
            - libtool-bin
          sources:
            - ubuntu-toolchain-r-test

install:
  # # set the proper C++ compiler
  # - export CXX=${_CXX}

  # # set the maximum number of cores supported on Travis
  # - JOBS=2

  # # dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/
  # - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  # - mkdir -p "${DEPS_DIR}"

  # # upgrade CMake to a more recent version
  # - CMAKE_VER=3.14.0
  # - CMAKE_URL="https://cmake.org/files/v${CMAKE_VER%.[0-9]}/cmake-${CMAKE_VER}-Linux-x86_64.tar.gz"
  # - curl -L ${CMAKE_URL} | tar xz -C ${DEPS_DIR}
  # - export PATH=${DEPS_DIR}/cmake-${CMAKE_VER}-Linux-x86_64/bin:${PATH}
  # - cmake --version
  # - cd ${TRAVIS_BUILD_DIR}

  # # install SystemC
  # - SYSC="systemc-2.3.3"
  # - sysc_url="https://www.accellera.org/images/downloads/standards/systemc/"
  # - curl -L ${sysc_url}${SYSC}.tar.gz | tar xz -C ${DEPS_DIR}
  # - mkdir -p ${DEPS_DIR}/${SYSC}/build
  # - cd ${DEPS_DIR}/${SYSC}/build && cmake -DCMAKE_CXX_STANDARD=11 .. && make -j${JOBS} && sudo make install
  # - cd ${TRAVIS_BUILD_DIR}

  # # install SST Core
  # - SSTCORE="sstcore-8.0.0"
  # - sst_core_url="https://github.com/sstsimulator/sst-core/releases/download/v8.0.0_Final/"
  # - mkdir -p ~/.sst
  # - touch ~/.sst/sstsimulator.conf
  # - curl -L ${sst_core_url}${SSTCORE}.tar.gz | tar xz -C ${DEPS_DIR}
  # - cd ${DEPS_DIR}/${SSTCORE} && ./configure --disable-dependency-tracking && make -j${JOBS} all && sudo make install
  # - cd ${TRAVIS_BUILD_DIR}

  # # install SST Elements
  # - SSTELEM="sstelements-8.0.0"
  # - sst_elem_url="https://github.com/sstsimulator/sst-elements/releases/download/v8.0.0_Final/"
  # - curl -L ${sst_elem_url}${SSTELEM}.tar.gz | tar xz -C ${DEPS_DIR}
  # - mv ${DEPS_DIR}/sst-elements* ${DEPS_DIR}/${SSTELEM}
  # - cd ${DEPS_DIR}/${SSTELEM} && ./configure --disable-dependency-tracking && make -j${JOBS} all && sudo make install
  # - cd ${TRAVIS_BUILD_DIR}

  # # install zmq
  # - LIBZMQ_VER="4.3.1"
  # - libzmq_url="https://github.com/zeromq/libzmq/archive/v${LIBZMQ_VER}.tar.gz"
  # - CPPZMQ_VER="4.3.0"
  # - cppzmq_url="https://github.com/zeromq/cppzmq/archive/v${CPPZMQ_VER}.tar.gz"
  # - curl -L ${libzmq_url} | tar xz -C ${DEPS_DIR}
  # - curl -L ${cppzmq_url} | tar xz -C ${DEPS_DIR}
  # - mkdir -p ${DEPS_DIR}/libzmq-${LIBZMQ_VER}/build
  # - cd ${DEPS_DIR}/libzmq-${LIBZMQ_VER}/build && cmake .. && sudo make -j${JOBS} install
  # - cd ${TRAVIS_BUILD_DIR}
  # - mkdir -p ${DEPS_DIR}/cppzmq-${CPPZMQ_VER}/build
  # - cd ${DEPS_DIR}/cppzmq-${CPPZMQ_VER}/build && cmake .. && sudo make -j${JOBS} install
  # - cd ${TRAVIS_BUILD_DIR}

  # # install msgpack
  # - ./install
  # - cd ${TRAVIS_BUILD_DIR}

before_script:
  - cd tests

script:
  - python --version
  - python3 --version
  - PYENV_VERSION=3.6.7
  - python3 --version
  - make --no-print-directory test
